apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-tls
spec:
  secretName: wildcard
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer  
  dnsNames:
    - "*.learnings.cluster.local"
    - "*.learnings"