apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-services
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        certmanager.k8s.io/cluster-issuer: 'selfsigned-issuer'
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
    tls:
      - hosts:
          - multicontainer.learnings        
        secretName: wildcard
    rules:
      - host: multicontainer.learnings
        http:
          paths:
            - path: /?(.*)
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
            - path: /api/?(.*)
              backend:
                serviceName: server-cluster-ip-service
                servicePort: 5000